#!/bin/sh
set -e

# Compile the upstream core, if it has been symlinked:
if [ -L ./node_modules/edge-login ]; then
  (
    cd ./node_modules/edge-login
    npm run build
  )
fi

# Compile the CLI:
./node_modules/.bin/rollup -c rollup.config.node.js
chmod +x ./bin/airbitz-cli

# Run the CLI:
./bin/airbitz-cli "$@"
